accounts/urls.py
from django.urls import path
from .views import SignupView , LoginView , LogoutView


app_name = 'accounts'
urlpatterns = [
    path('signup/', SignupView, name='signup'),
    path('login/', LoginView, name='login'),
    path('logout/', LogoutView, name='logout'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogg.urls')),
    path('accounts/', include('accounts.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogg/urls.py
from django.urls import path
from .views import BlogView, BlogDetail, AddPost, PostLike , PostUnlike

urlpatterns = [
    path('', BlogView.as_view(), name='home'),
    path('post/<pk>', BlogDetail.as_view(), name='detail'),
    path('addarticle/', AddPost, name='addarticle'),
    path('like/<postid>', PostLike, name='postlike'),
    path('unlike/<postid>', PostUnlike, name='postunlike'),
    
]

accounts/models.py
from django.db import models

# Create your models here.

blogg/models.py
from django.db import models
from django.contrib.auth.models import User



class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(User, on_delete= models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to= '%Y/%m/%d', null=True, blank=True)
    like = models.ManyToManyField(User , related_name='BlogLikes', blank=True)


    def __str__(self):
        return self.title


    def getsnippet(self):
        return self.content[0:100]

blogg/forms.py
from django import forms


class AddPostForm(forms.Form):
    title = forms.CharField(label='title' , max_length=200)
    content = forms.CharField(label='content' , widget=forms.Textarea)
    image = forms.ImageField(label='image')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import login , logout
from django.http import HttpResponse




def SignupView(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return render(request, 'accounts/login.html')

    else:
        form = UserCreationForm()
        return render(request, 'accounts/signup.html', {'form':form})





def LoginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

    form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})





def LogoutView(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

blogg/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Blog
from .forms import AddPostForm
from django.views import generic

def BlogPost(request):
    blog = Blog.objects.all()
    form = AddPostForm()
    context={'blogpost':blog}
    return render(request, 'home.html', context)



class BlogDetail(generic.DetailView):
    model = Blog
    template_name = 'blogg/blogdetail.html'



def AddPost(request):
    if request.method == "POST":
        form = AddPostForm(request.POST , request.FILES)

        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            writer = request.user
            image = form.cleaned_data['image']
            image = form.cleaned_data['video']
            blog = Blog.objects.create(title = title, content = content, writer = writer, image = image, video = video)
            blog.save()
            return render(request, 'blogg/successfully-add-post.html')

    else:
        form = AddPostForm()
        blog = Blog.objects.all()
    context = {'form':form}
    return render(request, 'blogg/add-article.html', context)




class BlogView(generic.ListView):
    template_name= 'blogg/home.html'
    context_object_name = 'blogpost'

    def get_queryset(self):
        return Blog.objects.all()


def PostLike(request, postid):
    post = Blog.objects.get(id = postid)
    user = request.user
    if user.is_authenticated:
        if user in post.like.all():
            return HttpResponse('!شما این پست را قبلا لایک کردید')
        post.like.add(user)
        return redirect('detail', postid)
    else:
        HttpResponse('یرای لایک کردن لطفا اول وارد سایت شوید')

    

def PostUnlike(request, postid):
    post = Blog.objects.get(id = postid)
    user = request.user
    if user.is_authenticated:
        if user in post.like.all():
            post.like.remove(user)
            return redirect('detail', postid)
        else:
            return HttpResponse('!شما این پست را لایک نکردید')
    else:
        HttpResponse('یرای لایک کردن لطفا اول وارد سایت شوید')

accounts/templates/accounts/base.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock title %}</title>
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/font/octicons.min.css"></head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'blogg/style.css' %}">
    
    <body id="body-home">
    
    
    {% if user.is_authenticated %}
      <!-- start navbar -->
    
      <nav class="navbar navbar-expand-xxl navbar-light bg-dark">
        <a class="navbar-brand" style="color:gold" href="../../">کالج بلاگ</a>
        <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <center><p style="color: rgb(0, 132, 255);">{{ user.username }} :نام کاربری شما<span class="sr-only">(current)</span></p></center>
            </li>
            <li class="nav-item active">
              <center><a style="color:gold" class="nav-link" href="../../">صفحه اصلی <span class="sr-only">(current)</span></a></center>
            </li>
            <li class="nav-item">
              <center><a style="color:gold" class="nav-link" href="../../addarticle">افزودن پست</a></center>            {% if user.is_authenticated %}
                    <center>
                      <form action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <button style="color:gold;background:dark;margin-top: 5px;" class="bg-dark" type="submit">logout</button>
                      </form>
                    </center>
                {% endif %}
            </li>
        </div>
      </nav>
    
    <!-- end navbar -->
    
    {% else %}
    <!-- start navbar -->
    
    <nav class="navbar navbar-expand-xxl navbar-light bg-dark">
      <a class="navbar-brand" style="color:gold" href="../../">کالج بلاگ</a>
      <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <center><a style="color:gold" class="nav-link" href="../../">صفحه اصلی <span class="sr-only">(current)</span></a></center>
          </li>
          <li class="nav-item">
            <center><a style="color:gold" class="nav-link" href="../../accounts/login">ورود</a></center>
            <center><a style="color:gold" class="nav-link" href="../../accounts/signup">ثبت نام</a></center>
          </li>
      </div>
    </nav>
    
    <!-- end navbar -->
    
    {% endif %}
    
    


    {% block content %}{% endblock content %}



    {% block footer %}{% endblock footer %}






    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}


{% block title %}{{ post.title }}{% endblock %}






{% block content %}


{% if user.is_authenticated %}
<script>window.alert("شما با موفقیت وارد سایت شدید");</script>
<center><h3 style="margin-top: 200px;margin-bottom: 200px;">!شما با موفقیت وارد سایت شدید</h3></center>
{% else %}

<center style="margin-top: 100px;margin-bottom: 150px;">
  <h1>ورود</h1><br><br>
  <form action="" method="POST">
      {{form}}
      {% csrf_token %}
      <br><br><br><button id="add-post-btn" type="submit">ورود</button>
  </form>
</center>

{% endif %}


{% endblock content %}




{% block footer %}

    <!-- Footer -->
<footer class="py-5 bg-dark" id="footer">
    <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; 2021</p><center><p id="copyright"> !تمام حقوق برای این وبسایت محفوظ است </p><hr>
    <a class="btn btn-warning btn-sm glyphicon glyphicon-eye-open" id="oloino" href="https://t.me/oloino" role="button">((( oloino  ساخته شده توسط )))</a>
    </div>
</footer>

{% endblock footer %}

accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}


{% block title %}{{ post.title }}{% endblock %}






{% block content %}


{% if user.is_authenticated %}

<center><h3 style="margin-top: 200px;margin-bottom: 200px;">!شما قبلا ثبت نام کردید</h3></center>


{% else %}

    <center style="margin-top: 75px;margin-bottom: 75px;">
    <h1>ثبت نام</h1>
        <form action="" method="POST">
            {{form}}
            {% csrf_token %}
            <br><br><br><button id="add-post-btn" type="submit">ثبت نام</button>
        </form>
    </center>

{% endif %}


{% endblock content %}




{% block footer %}

    <!-- Footer -->
    <footer class="py-5 bg-dark" id="footer">
        <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 2021</p><center><p id="copyright"> !تمام حقوق برای این وبسایت محفوظ است </p><hr>
        <a class="btn btn-warning btn-sm glyphicon glyphicon-eye-open" id="oloino" href="https://t.me/oloino" role="button">((( oloino  ساخته شده توسط )))</a>
        </div>
    </footer>
    
{% endblock footer %}

blogg/templates/blogg/add-article.html
{% extends 'blogg/base.html' %}


{% block title %}افزودن مطلب{% endblock %}







{% block content %}
  
  
  {% if user.is_authenticated %}

  <form enctype="multipart/form-data" action="{% url 'addarticle' %}" method="POST">
    {% csrf_token %}
    <center style="margin-top: 150px;margin-bottom: 150px;">
        {{ form }}
        <button id="add-post-btn" type="submit">افزودن مطلب</button>
    </center>
</form>

  {% else %}
  
  <center>
    <h3 style="margin-top: 125px;margin-bottom: 125px;margin-left: 20px;margin-right: 20px;">
      برای افزودن مطلب <a href="{% url 'accounts:signup' %}">ثبت نام </a>کنید و یا اگر اکانت دارید <a href="{% url 'accounts:login' %}">وارد</a>
      سایت شوید
    
    </h3>
  </center>
  {% endif %}
  
{% endblock content %}





    

{% block footer %}
<!-- Footer -->
<footer class="py-5 bg-dark" id="footer">
  <div class="container">
  <p class="m-0 text-center text-white">Copyright &copy; 2021</p><center><p id="copyright"> !تمام حقوق برای این وبسایت محفوظ است </p><hr>
  <a class="btn btn-warning btn-sm glyphicon glyphicon-eye-open" id="oloino" href="https://t.me/oloino" role="button">((( oloino  ساخته شده توسط )))</a>
  </div>
</footer>
<!-- end Footer -->
{% endblock footer %}

blogg/templates/blogg/base.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock title %}</title>
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/font/octicons.min.css"></head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'blogg/style.css' %}">
    
    <body id="body-home">
    
    
    {% if user.is_authenticated %}
      <!-- start navbar -->
    
      <nav class="navbar navbar-expand-xxl navbar-light bg-dark">
        <a class="navbar-brand" style="color:gold" href="../">کالج بلاگ</a>
        <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <center><p style="color: rgb(0, 132, 255);">{{ user.username }} :نام کاربری شما<span class="sr-only">(current)</span></p></center>
            </li>
            <li class="nav-item active">
              <center><a style="color:gold" class="nav-link" href="../">صفحه اصلی <span class="sr-only">(current)</span></a></center>
            </li>
            <li class="nav-item">
              <center><a style="color:gold" class="nav-link" href="../addarticle">افزودن پست</a></center>            {% if user.is_authenticated %}
                    <center>
                      <form action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <button style="color:gold;background:dark;margin-top: 5px;" class="bg-dark" type="submit">logout</button>
                      </form>
                    </center>
                {% endif %}
            </li>
        </div>
      </nav>
    
    <!-- end navbar -->
    
    {% else %}
    <!-- start navbar -->
    
    <nav class="navbar navbar-expand-xxl navbar-light bg-dark">
      <a class="navbar-brand" style="color:gold" href="../">کالج بلاگ</a>
      <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <center><a style="color:gold" class="nav-link" href="../">صفحه اصلی <span class="sr-only">(current)</span></a></center>
          </li>
          <li class="nav-item">
            <center><a style="color:gold" class="nav-link" href="../accounts/login">ورود</a></center>
            <center><a style="color:gold" class="nav-link" href="../accounts/signup">ثبت نام</a></center>
          </li>
      </div>
    </nav>
    
    <!-- end navbar -->
    
    {% endif %}
    


    {% block content %}{% endblock content %}



    {% block footer %}{% endblock footer %}






    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

blogg/templates/blogg/blogdetail.html
{% extends 'blogg/base.html' %}


{% block title %}{{ blog.title }}{% endblock %}






{% block content %}


{% if user.is_authenticated %}

<br><br>

<center>

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{ blog.image.url }}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{blog.title}}</h5>
    <h5 class="card-title">{{blog.writer}} :نویسنده</h5>
    <h5 class="card-title">{{blog.date}}</h5><hr>
    <p class="card-text">{{ blog.content }}</p>
  </div>
</div>

</center>
<center>

  <br>
  <br>

  {% if user in blog.like.all %}
      <b><a href="{% url 'postunlike' blog.id %}" style="background: rgb(255, 25, 25);color: black;font-size: large;" class="btn btn-sm glyphicon glyphicon-eye-open">unlike</a>
  {% else %}
      <a href="{% url 'postlike' blog.id %}" style="background: rgb(60, 255, 0);color: black;font-size: larger;"  class="btn btn-warning btn-sm glyphicon glyphicon-eye-open">like</a>
  {% endif %}

</center>



<br><br><br><br><br><br>

{% else %}
<center>
  <h3 style="margin-top: 125px;margin-bottom: 125px;margin-left: 20px;margin-right: 20px;">
    برای نمایش مطلب <a href="{% url 'accounts:signup' %}">ثبت نام </a>کنید و یا اگر اکانت دارید <a href="{% url 'accounts:login' %}">وارد</a>
    سایت شوید
  </h3>
</center>
<br><br><br>
{% endif %}


{% endblock content %}







{% block footer %}

<!-- Footer -->
<footer class="py-5 bg-dark" id="footer">
  <div class="container">
  <p class="m-0 text-center text-white">Copyright &copy; 2021</p><center><p id="copyright"> !تمام حقوق برای این وبسایت محفوظ است </p><hr>
  <a class="btn btn-warning btn-sm glyphicon glyphicon-eye-open" id="oloino" href="https://t.me/oloino" role="button">((( oloino  ساخته شده توسط )))</a>
  </div>
</footer>
<!-- end Footer -->

{% endblock footer %}

blogg/templates/blogg/home.html
{% extends 'blogg/base.html' %}
{% block title %}صفحه اصلی{% endblock title %}



{% block content %}
<center>
  <br><br><h1 style="color: white;">بِسْمِ ٱللَّٰهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ</h1><br><br><hr><hr><hr><br>
</center>

    


<div class="row row-cols-3">
  {% for post in blogpost %}
  <div class="col">
    <div class="card" style="margin-left: 15px;margin-right: 15px;text-align: right;">
      <img class="card-img-top" src="{{ post.image.url }}" width="500" alt="">
        <div class="card-body">
            <h5 style="margin-top:20px">{{ post.title }}</h5><br>
            <p style="margin-top:20px">{{ post.getsnippet }}</p><br>
            <a class="btn btn-warning btn-lg glyphicon glyphicon-eye-open" style="border-radius: 20px; " href="{% url 'detail' post.id %}" role="button"> مشاهده مطلب</a><br><hr>
            <p>{{ post.writer }} :نویسنده</p>
            <p>{{ post.date }} :تاریخ انتشار</p>
        </div>  
    </div>
  </div><br>
  {% endfor %}
</div></div><br>



<br><br><br><br>

{% endblock content %}




{% block footer %}

<footer class="py-5 bg-dark" id="footer">
    <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; 2021</p><center><p id="copyright"> !تمام حقوق برای این وبسایت محفوظ است </p><hr>
    <a class="btn btn-warning btn-sm glyphicon glyphicon-eye-open" id="oloino" href="https://t.me/oloino" role="button">((( oloino  ساخته شده توسط )))</a>
    </div>
</footer>

{% endblock footer %}

blogg/templates/blogg/successfully-add-post.html
{% extends 'blogg/base.html' %}


{% block title %}پست با موفقیت افزوده شد{% endblock %}






{% block content %}


<b><center style="margin-top: 15%;"><h1>!پست با موفقیت افزوده شد</h1></center></b>
<center style="margin-top: 5%;">
    
<a class="btn btn-warning btn-lg glyphicon glyphicon-eye-open" href="../"  style="font-size: 20px;border-radius: 10px;padding-bottom: 5px;background: black;color: gold;" role="button"> بازگشت به صفحه اصلی</a><br><br><br>

</center>

{% endblock content %}



{% block footer %}

<footer class="py-5 bg-dark" id="footer">
    <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; 2021</p><center><p id="copyright"> !تمام حقوق برای این وبسایت محفوظ است </p><hr>
    <a class="btn btn-warning btn-sm glyphicon glyphicon-eye-open" id="oloino" href="https://t.me/oloino" role="button">((( oloino  ساخته شده توسط )))</a>
    </div>
</footer>

{% endblock footer %}